enyo.depends(
	"$lib/enyo-webos",
	"$lib/garnet",
	"Common.css",
	"PanelStack.js",
	"Main.js",
	"ButtonSample.js",
	"SpinnerSample.js",
	"WheelSliderControllerSample.js",
	"DataListSample.js",
	"PanelSetSample.js",
	"BloodInfoSample.js",
	"SearchMapSample.js",
	"MyBloodSample.js",
	"MapSample.js",
	"MapSample.css",
	"PopupSample.js",
	"PopupSample.css"
);
